# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for A3
  pod 'Alamofire'
end
