# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A4' do
  use_frameworks!

  # Pods for A4

  pod 'SnapKit'
  pod 'Alamofire'
  pod 'SDWebImage'
end