//
//  UIColor+Extension.swift
//  A3
//
//  Created by Vin Bui on 10/31/23.
//

import UIKit

extension UIColor {

    // DO NOT EDIT THIS FILE

    static let a3 = A3()

    struct A3 {
        let black = UIColor.black
        let offWhite = UIColor(red: 249/255, green: 249/255, blue: 249/255, alpha: 1)
        let ruby = UIColor(red: 202/255, green: 66/255, blue: 56/255, alpha: 1)
        let silver = UIColor(red: 191/255, green: 191/255, blue: 191/255, alpha: 1)
        let white = UIColor.white
    }

}
