//
//  UIColor+Extension.swift
//  A2
//
//  Created by Vin Bui on 6/4/23.
//

import UIKit

extension UIColor {
    
    // DO NOT EDIT THIS FILE
    
    static let a2 = A2()
    
    struct A2 {
        let black = UIColor.black
        let ruby = UIColor(red: 202/255, green: 66/255, blue: 56/255, alpha: 1)
        let silver = UIColor(red: 191/255, green: 191/255, blue: 191/255, alpha: 1)
        let systemBlue = UIColor.systemBlue
        let white = UIColor.white
    }

}
